const challengeDays = [
  ["Procrastination is a system, not a character flaw", "What exactly happens when I delay?", "I tend to... when...", "Start the Procrastination Diagnostic Map", "60-90 second baseline + 120-word text"],
  ["Types of delay", "What kind of procrastination do I use most?", "It feels like..., but actually...", "Classify three delayed tasks", "Three clear delay categories"],
  ["The real cost of delay", "What does procrastination cost me?", "Cause and effect clauses", "Write the honest cost of one delayed task", "A cost paragraph"],
  ["Avoidance and self-image", "What does this task threaten to reveal about me?", "I may be avoiding... because...", "Map one avoided task to fear, status, or uncertainty", "A personal avoidance map"],
  ["Diagnostic checkpoint", "Why do I procrastinate?", "Story structure and clear links", "Finish the first version of the diagnostic map", "90-second story + 120-word text"],
  ["Values before mood", "What is worth doing even when I do not feel ready?", "Even when..., I can still...", "List five values that should guide action", "A values mini-talk"],
  ["Responsibility without self-punishment", "What is one zone I can actually control?", "Can, cannot, should, do not have to", "Choose one controllable work zone", "A realistic responsibility statement"],
  ["Future self as a real person", "What would my future self want me to start now?", "Future forms + reasons", "Write a short letter from one year ahead", "A future-self voice note"],
  ["Micro-promises", "What promise is small enough to keep under stress?", "I can commit to...", "Create one ten-minute daily promise", "A promise you can actually keep"],
  ["Action contract checkpoint", "Why is this course worth finishing?", "Reasons, examples, and results", "Finish the Personal Action Contract", "Two-minute talk + 150-word text"],
  ["Body state and work", "What minimum state do I need to start useful work?", "I work better when...", "Build a basic energy checklist", "A useful-state explanation"],
  ["Sleep, light, and movement", "Which physical lever gives me the best start?", "Comparatives", "Test one morning or pre-work reset", "A comparison + one experiment"],
  ["Dopamine and fast rewards", "Which quick reward pulls me away from work?", "I am tempted to... because...", "Audit three fast-reward loops", "A distraction explanation"],
  ["Stress: mobilization or paralysis", "When does pressure help me, and when does it freeze me?", "Whereas, while, rather than", "Design one reset before difficult work", "A contrast answer + reset"],
  ["Energy protocol checkpoint", "How do I prepare my body and mind for work?", "Input retell + protocol explanation", "Finish the Energy Protocol", "A two-minute protocol explanation"],
  ["Automatic thoughts", "Which thoughts trigger avoidance?", "I tell myself that...", "Collect ten avoidance thoughts", "A thought-pattern report"],
  ["A thought is not a fact", "What evidence supports or challenges this thought?", "Contrast and evidence phrases", "Fill a thought, evidence, and alternative table", "An evidence-based response"],
  ["Perfectionism as disguised avoidance", "When do I hide behind quality standards?", "Good enough to...", "Define a good-enough version of one task", "A good-enough decision"],
  ["Action with discomfort", "Which value can I act on while feeling discomfort?", "I can feel... and still...", "Work for 10-25 minutes with discomfort present", "A discomfort action story"],
  ["Avoidance checkpoint", "What am I really avoiding?", "Story, contrast, and explanation", "Finish the CBT/ACT Avoidance Map", "Three-minute story + map"],
  ["Motivation is a weak starter", "Why should I not wait for motivation?", "I used to think..., but now...", "List actions that can start without motivation", "An old-belief / new-belief answer"],
  ["Implementation intentions", "What will I do if resistance appears?", "If..., I will...", "Write ten if-then start scripts", "A start-script library"],
  ["The next physical action", "What does this task look like as a physical action?", "Infinitive for purpose", "Rewrite five vague tasks into physical actions", "A clear action list"],
  ["Two-minute entry point", "How can I make the task small enough to start?", "Instead of..., I can...", "Test a two-minute start", "A before-and-after explanation"],
  ["Start scripts checkpoint", "How do I start before I feel ready?", "Problem-solution structure", "Finish the If-Then Start Script Library", "Three-minute problem-solution answer"],
  ["Friction design", "How can I make the right action easier?", "I can reduce friction by...", "Remove three work barriers", "A friction audit"],
  ["Attention residue", "Why is switching between tasks expensive?", "Cause, effect, and examples", "Run one block with no switching", "A focus experiment"],
  ["Digital noise", "Which digital channel steals the most attention?", "I lose focus when...", "Clean or block one channel", "A digital-boundary explanation"],
  ["Entering focus", "What is my personal protocol for entering focus?", "First..., then..., after that...", "Build a three-to-five-minute start ritual", "A process explanation"],
  ["Focus checkpoint", "How do I protect deep work?", "Linking, reflection, and Present Perfect", "Finish the start ritual and first Deep Work Calendar", "Four-minute talk + 250-word reflection"],
  ["Output versus motion", "What looks productive but is not real output?", "There is a difference between...", "Audit one day for output versus preparation", "An output audit"],
  ["Deliverables", "What visible result should this task produce?", "The outcome should be...", "Define one concrete deliverable", "A deliverable statement"],
  ["Planning without overplanning", "When does planning become avoidance?", "The hidden cost is...", "Limit planning and create a first draft", "A planning-boundary story"],
  ["Feedback loops", "What feedback do I need from action?", "Action shows me whether...", "Finish a small test and record feedback", "A test-result explanation"],
  ["Workplace update", "What did I achieve, what blocked me, and what will I do next?", "Clear workplace status update", "Produce one written or spoken update", "A professional progress update"],
  ["Missing a day", "How do I return after failure without drama?", "When I miss..., I will...", "Write a restart rule", "A recovery rule"],
  ["Shame and recovery", "How can I repair the system without attacking myself?", "What went wrong was...", "Debrief one failed attempt", "A calm debrief"],
  ["Rest versus avoidance", "How do I know if I need rest or if I am escaping?", "Rest helps..., whereas avoidance...", "Compare one rest case and one avoidance case", "A useful contrast"],
  ["Rebuilding trust", "How do I rebuild trust through small proof?", "Present Perfect for progress", "Keep one small promise and record proof", "A progress update"],
  ["Recovery checkpoint", "How do I recover and keep working?", "Fluency, self-correction, and argument clarity", "Finish the Anti-Procrastination Protocol", "Five-minute simulation + 300-word essay"],
  ["Personal work system", "How does my system operate from idea to output?", "Process explanation", "Map inbox, calendar, tasks, and review", "A system walkthrough"],
  ["Priorities and trade-offs", "What should I not do right now?", "I am choosing X over Y because...", "Create a not-now, not-mine, not-worth-it list", "A trade-off explanation"],
  ["Metrics without neurosis", "How do I measure progress without turning it into pressure?", "A better measure would be...", "Choose three behavior metrics", "A measurement argument"],
  ["Explaining the system at work", "How would I explain my work system in an interview?", "Interview story structure", "Write an interview answer", "A job-ready explanation"],
  ["System checkpoint", "What is my personal work system?", "Explanation plus follow-ups", "Finish the Personal Work System", "Five-minute explanation"],
  ["Hard days", "How do I work when conditions are bad?", "Conditionals and clarification", "Build a minimum viable action protocol", "A bad-day protocol"],
  ["Identity and ambition", "What kind of person am I practicing becoming?", "Realistic identity language", "Write a realistic work identity statement", "A grounded identity statement"],
  ["Manual for me", "What advice would I give myself before starting hard work?", "I would tell myself to...", "Draft the Manual for Me", "A personal advice talk"],
  ["After-course plan", "How will I keep this system alive for 30 days?", "Future plan + constraints", "Create a 30-day continuation plan", "A continuation plan"],
  ["Final defense", "How do I start hard things when motivation is low?", "Final integration", "Finish the essay and oral defense", "450-word essay + 5-7 minute oral defense"],
].map(([topic, question, focus, artifact, evidence], index) => ({
  day: index + 1,
  topic,
  question,
  focus,
  artifact,
  evidence,
}));

const challengePhases = [
  { name: "Diagnose", range: [1, 5], color: "coral" },
  { name: "Commit", range: [6, 10], color: "gold" },
  { name: "Energize", range: [11, 15], color: "mint" },
  { name: "Unpack", range: [16, 20], color: "violet" },
  { name: "Start", range: [21, 25], color: "blue" },
  { name: "Focus", range: [26, 30], color: "teal" },
  { name: "Deliver", range: [31, 35], color: "orange" },
  { name: "Recover", range: [36, 40], color: "pink" },
  { name: "Systemize", range: [41, 45], color: "indigo" },
  { name: "Integrate", range: [46, 50], color: "lime" },
];

const challengeAchievements = [
  { id: "first-step", icon: "01", title: "First Step", detail: "Complete your first mission.", test: (state) => state.completed.length >= 1 },
  { id: "five-day", icon: "05", title: "Five-Day Signal", detail: "Complete the first five days.", test: (state) => state.completed.length >= 5 },
  { id: "ten-day", icon: "10", title: "First Checkpoint", detail: "Complete the first ten missions.", test: (state) => state.completed.length >= 10 },
  { id: "halfway", icon: "25", title: "Halfway Human", detail: "Reach the middle of the lab.", test: (state) => state.completed.length >= 25 },
  { id: "system", icon: "45", title: "System Builder", detail: "Finish your personal work system.", test: (state) => state.completed.length >= 45 },
  { id: "defense", icon: "50", title: "Oral Defense", detail: "Complete the final mission.", test: (state) => state.completed.length >= 50 },
];
